index.d.ts
As the title says, this PR adds TypeScript support.
Import the StatusBar package and check if the types are there or not 😅
=> feat: add TypeScript support

README.md
This PR is part of react-native-community/.github#45
Added LeanCore extracted badge in README.
=> chore: add lean core badge

README.md
Added Linking instructions to README
=> Add Linking instructions to README

README.md
Update screenshot and badges in README
=> Update screenshot and badges in README

README.md
=> Fix license badge on README

CONTRIBUTING.md, README.md, RNCClipboard.podspec, package.json
Update the url of the repo
example works with the new podspec
=> chore: update url of the repo

README.md, example/App.tsx, example/index.js, example/ios/Podfile.lock, src/index.ts, src/useClipboard.ts
Adding the useClipboard hooks from the community hooks library https://github.com/react-native-community/hooks
Test on android and ios simulator
=> feat: add useClipboard hooks

.circleci/config.yml, package.json, src/useClipboard.ts, yarn.lock
Updated community eslint config
=> chore: update lint config

android/build.gradle, package.json
Fixes #45 
Fix syntax of peerDependency to remove the peerDependency warning
tested that warning won't show up when installing from forked repo
=> chore: fix peer dependnecies

.circleci/config.yml, package.json
=> chore: update orb

README.md
=> Remove unnecessary arrow functions at example

README.md
Although it seems obvious, newer developers may not know to run install pods after installing this library. This PR adds a simple line to the readme file instruction the user to run pod install.
It's an update to a readme file. No testing needed.
=> Update Readme to include instructions to install pods

.flowconfig, example/.flowconfig
This PR aims to fix the ci for flow check by adding max workers for circleci
=> chore: add max workers for flowconfig

README.md, example/App.tsx, example/ios/Podfile.lock, ios/RNCClipboard.m, src/Clipboard.ts
add `hasURL` method which checks whether the content on Clipboard is a URL or not without triggering notification for iOS14+
Tested on iOS simulator.
=> feat: add hasURL method

src/Clipboard.ts
Fixed Lint error that was causing ci to fail
=> Chore: fix lint

src/Clipboard.ts
Closes #98 
Fixed jsdoc for hasURL method
=> docs: fix jsdoc for hasURL

README.md, __tests__/mock.test.js, jest/clipboard-mock.js, package.json
Fixes #107 
Added mock setup file for clipboard module
=> feat: add clipboard mock

README.md, ios/RNCClipboard.m, src/Clipboard.ts
feature: hasNumber(iOS 14+ only)
Returns whether the clipboard has a Number(UIPasteboardDetectionPatternNumber) content.
Can check if there is a Number content in clipboard without triggering PasteBoard notification for iOS 14+
feature: hasWebURL(iOS 14+ only)
Returns whether the clipboard has a WebURL(UIPasteboardDetectionPatternProbableWebURL) content.
Can check if there is a WebURL content in clipboard without triggering PasteBoard notification for iOS 14+
=> feat: hasNumber & hasWebURL

package.json
=> chore: fix build script

src/Clipboard.ts
Apply lint that was causing the CI to fail
CI to pass
=> chore: apply format

.github/workflows/ci.yml
=> Update node version in Github actions

.github/workflows/ci.yml
removed node 16 from ci as it reached EOL
=> Update node version in ci

android/build.gradle
=> fix - monorepo build

.eslintrc.js
=> fix: eslint config

.github/workflows/ci.yml
=> fix: android ci

package.json
Please review this request to avoid adding unnecessary dependencies to a mobile-only react-native project.
This is the same kind of change as this PR : #240
=> Mark react-native-macos as optional

android/src/paper/java/com/reactnativecommunity/clipboard/NativeClipboardModuleSpec.java
=> fix: type in spec file

package.json, yarn.lock
moved dependencies to dev dependencies so it doesnt force version
=> fix: move unnecessary deps to dev deps

example/android/gradle/wrapper/gradle-wrapper.properties
=> fix: update gradle version
