react-native-clipboard/clipboard

package.json
yarn.lock

removed `babel-plugin-module-resolver` as it is no longer used.
also added `@babel/core` as a devDependencies because the metro-preset has it as peer dependency
CI Passes

chore: remove unused package and add babel/core

---

ios/RNCClipboard.xcodeproj/project.pbxproj

Fixes #44 
Removing development team which is not required for library usage
works with ios simulator

fix: remove team from xcode project

---

README.md

We've been recommending devs use `npx pod-install` since it will attempt to install CocoaPods CLI if it's not available on the computer (cite [React Navigation setup guide](https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project)). This has proved very useful for Expo users who are now migrating to the bare workflow and want to use community packages in their projects.

docs: Recommend npx pod-install for setup instructions

---

android/build.gradle

I don't think `conscrypt-android` is necessary. This library makes the APK size unnecessarily large.
None

Removed an unnecessary library on Android

---

RNCClipboard.podspec

The latest Xcode 12 fails to build when a module does not depend on `React-Core` directly. This change is necessary for all native modules on iOS. For details please see: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
1. Build an App with Xcode 11.x. Result: The app builds.
2. Build an App with Xcode 12. Result: The app will not build when depending on `React`.
3. Build an App with Xcode 12 with the PR changes applied. Result: The app builds.

fix: Xcode 12 compatibility

---

.github/workflows/ci.yml
README.md

Since CI has been changed to GHA in #76 , I've changed the Badge on README to show correct status for CI

docs: replace CircleCI badge with GHA badge on README

---

android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
ios/RNCClipboard.m
src/Clipboard.ts
src/NativeClipboard.ts

Firstly, thanks for the work on the clipboard!
iOS 14 now shows a notification each time an app accesses the clipboard, so we need to be more careful on when to read it. It also has a new API that allows apps to tell if there's any content on the clipboard or not. The API has more methods than the one I implemented, I just added the one I needed. I don't have time to keep working on this unfortunately to add the rest of the methods :( I understand if you think this is not enough to merge.
Unfortunately, the example project didn't compile for me, so I couldn't use that one to test, I tested directly on my own project.
To test you need an iOS 14 device and one with an older version. On both of them add a call somewhere to `await Clipboard.hasString()`. Do so while having content on the …

feat: Expose hasString method for iOS 14+

---

windows/Clipboard/Clipboard.vcxproj

Fix error produced when module is added to a React Native app and run in Windows emulator.
Error reads: "The target "Deploy" does not exist in the project".
Create a React Native Windows app.
Add datetimepicker module to app via `yarn add`.
Run `npx react-native run-windows`.
If app deploys successfully and loads in the Windows emulator, the code change has succeeded.

Resolve Missing Deploy Target for Windows

---

CONTRIBUTING.md
README.md
RNCClipboard.podspec
package.json

part of react-native-community/discussions-and-proposals#330
moving this package to `@react-native-clipboard/clipboard`

feat: migrate to different namespace

---

ios/RNCClipboard.m
src/Clipboard.ts

Added the ability to check if there is an image in the iOS Pasteboard and to retrieve clipboard image if it exists as base64 png/jpg.
Tested each function with various cases (no image in clipboard, etc) with a simple test application and the behavior was as expected. Open to any ideas on corner cases to check/explore.

Retrieve images from iOS Pasteboard

---

android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
example/App.tsx
ios/RNCClipboard.h
ios/RNCClipboard.m
src/Clipboard.ts
src/NativeClipboard.ts

Closes https://github.com/react-native-clipboard/clipboard/issues/92
Implement change listeners to get notified on the JS side when the clipboard has changed. Thanks to https://github.com/stefanc96/react-native-clipboard-listener for the amazing idea.
Tested on the iOS simulator using the example project.
Tested on a real iOS device (iPhone 12 Pro, 14.4.x), using an internal project (as the example can't be run on a device)
Tested on a real Android device (Pixel 5, Android 11) using an internal project (as the example project doesn't even work with the run-android command)
Looking forward to getting this reviewed and merged.

feat: implement clipboard change listener

---

src/NativeClipboard.ts

Fixes a `EventEmitter` usage to work with RN 0.64 and older. Refer to https://github.com/react-native-clipboard/clipboard/pull/97
Tested on RN 0.62.2 and RN 0.64.2

fix listener for older RN versions

---

src/NativeClipboard.ts

Yet another fix for the event listener changes.  Make sure the `remove` call also clears the native listener if there are any left.
I could not find any useful API in the EventEmitter class to do this nicely, so the approach is to just patch the remove method to do the cleanup once it is the last listener. Any other ideas are welcome.
Code change that caused the bug initially: https://github.com/react-native-clipboard/clipboard/commit/08a2c005ea06f5e8501ff512f19f560dea22b700#diff-cdaf1c3ad4529370d3d7c0daa193662c1f00974d8975aa4bb588d00fc441ad44L26
Related: https://github.com/react-native-clipboard/clipboard/pull/104
Tested `remove` calls on both iOS and Android.
@Naturalclar any ideas on how the cleanup code can be implemented without monkey-patching?

Fix even listener remove

---

src/NativeClipboard.ts

if it's not polyfilled, extracted listenerCount will lose context, and `this` will be undefined.
Before this change, calls like this
```
Clipboard.addListener(handler);
```
will throw on app with React native version of 0.64 or newer

fix: calls to listenerCount throw for RN 0.64+

---

android/build.gradle

jCenter will be offline in February 2022. I've updated the android project to use maven.
I've tested the library on a personal project and it builds without issues.

chore(android): replaced jCenter with mavenCentral

---

__tests__/mock.test.js
jest/clipboard-mock.js

In the previous mock, the clipboard methods (except the hook) were exposed under `Clipboard` key.
As a consequence the mock was not working.
Why ? 
If you look in the file (index.ts)[https://github.com/react-native-clipboard/clipboard/blob/master/src/index.ts], these methods are exported as default, **NOT** under a Clipboard key.
I fixed the test file but it is not very usefull because it do not really mock the module.
It just test an implementation (the mock implementation).
Do not know for the moment how to improve this part.
Any idea ?

Fix mock exports

---

README.md
ios/RNCClipboard.m
src/Clipboard.ts

feature: getStrings + setStrings (iOS only)
iOS's native clipboard API supports string array, so here I add wrapper methods for it.
```
@property(nullable,nonatomic,copy) NSArray<NSString *> *strings API_UNAVAILABLE(tvos) API_UNAVAILABLE(watchos);
```

feat: getStrings + setStrings

---

android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java

Fixes #151 
Fix: Allow Clipboard module to be used with targetSdkVersion 30

Fix: Allow Clipboard module to be used with targetSdkVersion 30

---

windows/Clipboard/Clipboard.vcxproj

Clipboard has been using an older toolset which is becoming outdated and causing ` Error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution` in React-Native-Windows .71 and any future versions.
The fix is to remove the specified toolset and use the standard version.
Tested locally on React-Native-Windows Gallery and in a React-Native .68 application. Looks like example app is broken in this repository.

Remove windows specified Platform Toolset

---

windows/Clipboard/Clipboard.vcxproj

In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72
tested on react native windows gallery

fix: windows bump WindowsTargetPlatformMinVersion 

---

windows/Clipboard/Clipboard.cpp
windows/Clipboard/Clipboard.h

Fixes #173
I have made this change locally in my Windows app and validated this fixes the crash.
I also tested `getString`, which already worked and needed to changes.

Fix setString on Windows by dispatching to UI thread

---

package.json
src/NativeClipboard.ts

I have added the Turbo Module support since it's officially released from RN version 0.68 and upgraded the ReactNative version to 0.68.
Tested the Turbo Module support in iOS and Android platforms only Windows and macOS are still remaining.

new arch. support for ios and android config

---

.github/workflows/ci.yml
example/ios/Podfile
example/ios/Podfile.lock
package.json
src/NativeClipboard.ts
yarn.lock

Change node version on CI

---

android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java

Notice that in the line `ClipData.Item firstItem = clipboard.getPrimaryClip().getItemAt(0);`, you're calling `getPrimaryClip()` again instead of using the already retrieved `clipData` object. If there's no primary clip at this point (it could have been changed by another process or thread after the initial `getPrimaryClip()` call), `getPrimaryClip()` will return `null`, and trying to call `getItemAt(0)` on it will result in the error you're seeing.
Error log:
```
Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
```

Use existing clipData instead of calling getPrimaryClip() again

---

windows/Clipboard/Clipboard.vcxproj

Fix SDK build error if 10.0.18362.0 is not installed:
```
× Building Solution: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft...
× Build failed with message C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```
See https://github.com/react-native-async-storage/async-storage/pull/810 for a similar fix.
Previously, after bringing down package dependencies you'd have to retarget the SDK version for the module project.
Committed to a fork and …

Remove explicit SDK version for Windows builds

---

ios/RNCClipboard.m
macos/RNCClipboard.m

Fixes #116 
Similar fix applied on #175 but for iOS/Macos supresses the NativeEventEmitter warning
Build/Open the  Macos or iOS apps and you should see no warning
Reference: https://github.com/react-native-netinfo/react-native-netinfo/pull/487

Fix warnings: new NativeEventEmitter() was called with a non-null argument

---

RNCClipboard.podspec

https://github.com/react-native-clipboard/clipboard/commit/7f84dabcee9789ed9933ff236f5fad373e1400b1 accidentally removed the `osx` key from the defined platforms inside the podspec
Run pod install in a macOS project and ensure that RNCClipboard is not removed

Add macOS back to podspec platforms

---

jest/clipboard-mock.js

we recently switched our clipboard library from `@react-native-community/clipboard` to `@react-native-clipboard/clipboard`. On running our unit test suite I noticed this error : 
```
/Users/siddarthkumar/code/experiments/status-mobile/target/unit_test/test.js:67
throw e;
^
TypeError: Cannot read properties of undefined (reading 'getEnforcing')
at Object.<anonymous> (/Users/siddarthkumar/code/experiments/status-mobile/node_modules/
@react-native-clipboard/clipboard/dist/NativeClipboardModule.js:5:63)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Function.hookedLoader [as _load] …
```

add missing `getEnforcing` jest mock

---

android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
android/src/paper/java/com/reactnativecommunity/clipboard/NativeClipboardModuleSpec.java

I get the following build error on Android with **new architecture** enabled.
Created a test app using the guide here: https://gist.github.com/cipolleschi/82b7a9561b8861330efabbd3eb08c6f5#file-test-your-library-against-react-native-0-74-0-rcs-md
RN version: 0.74.0-rc.9
```
/src/ClipboardTest/node_modules/@react-native-clipboard/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:39: error: ClipboardModule is not abstract and does not override abstract method removeListeners(int) in NativeClipboardModuleSpec
public class ClipboardModule extends NativeClipboardModuleSpec {
^
/src/ClipboardTest/node_modules/@react-native-clipboard/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:240: error: method does not override or …
```

fix: module spec mis-match on Android (new Architecture)

---

android/src/main/AndroidManifest.xml

When building with Gradle > 8 we get this error:
```
Execution failed for task ':@react-native-community_clipboard:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
> Incorrect package="com.reactnativecommunity.clipboard" found in source AndroidManifest.xml: /node_modules/@react-native-community/clipboard/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.reactnativecommunity.clipboard" from the source AndroidManifest.xml: node_modules/@react-native-community/clipboard/android/src/main/AndroidManifest.xml.
```
I removed this line: `package="com.reactnativecommunity.clipboard` …

chore: Update AndroidManifest.xml to support AGP > 8

---

README.md
ios/RNCClipboard.mm
src/Clipboard.ts
src/NativeClipboardModule.ts

Added `getImage` support for iOS. 
1. Copy JPEG image
2. Paste the image and verify it's pasted as jpeg
3. Copy PNG image
4. Paste the image and verify it's pasted as png
5. Copy GIF image
6. Paste the image and verify it's pasted as gif
https://github.com/user-attachments/assets/2231b890-8698-49bf-be40-461d79607fc7
https://github.com/user-attachments/assets/699eea6f-3b97-4df8-be25-ab54d0821d6a

feat: getImage iOS

---

.github/workflows/ci.yml
package.json
react-native.config.js

fix: ios ci invalid options

---

ios/RNCClipboard.mm
macos/RNCClipboard.m

At my side of Microsoft, we have recently "vendored" a couple of libraries. Which means, we started building them from source using our own generated Xcode project (not the one cocoapods generates), which has much stricter build flags / treats warnings as errors. In doing so, I caught a couple of issues in React Native Clipboard I'd like to push back up!
Namely:
- Adding `__unused` clang tags
- Changing types from `NSInteger` to `double`
CI should pass, and changes are mostly innocuous

chore(apple): fix build issues found internally

---

android/src/main/java/com/reactnativecommunity/clipboard/ClipboardPackage.java

This PR fixes an initialization error on Android while using `@react-native-clipboard/clipboard` in a React Native 0.80.0-rc.0 app. See https://github.com/facebook/react-native/blob/77c1eb615400c07fd2a7d7f4a47dd87cef1c8743/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactInstance.kt#L544-L545. Note that `addAll` method requires the argument to be non-null.

Return empty list instead of null from `getViewManagerNames`
